name: AnnouncerPlus-OG
version: $version
main: xyz.jpenilla.announcerplus.AnnouncerPlus
description: $description
authors: [jmp, NotAlexNoyle]
website: $website
api-version: $apiVersion
softdepend:
  - PlaceholderAPI
  - Essentials
  - ViaVersion
folia-supported: true
